#pragma once
#define PLUGIN_VERSION_DEV     0
#define PLUGIN_VERSION_BETA    1
#define PLUGIN_VERSION_RELEASE 2



#define LLNET_INFO_LOADER_NAME "LiteLoader.NET"

#define LLNET_INFO_LOADER_DESCRIPTION "LiteLoaderBDS bindings for .NET"

#define LLNET_INFO_AUTHOR "LiteLoaderBDS .NET Developers"

#define LLNET_INFO_COPYRIGHT "Copyright (c) 2020-2022 LiteLoaderBDS Developers"



#define LLNET_VERSION_MAGOR 2

#define LLNET_VERSION_MINOR 9

#define LLNET_VERSION_REVISION 0

#define LLNET_VERSION_BUILD 0

#define LLNET_VERSION_STATUS PLUGIN_VERSION_DEV
