#pragma once

#define __TO_VERSION_STRING(ver) #ver

#define TO_VERSION_STRING(ver) __TO_VERSION_STRING(ver)



#define LLNET_VERSION_MAGOR 2

#define LLNET_VERSION_MINOR 4

#define LLNET_VERSION_REVISION 2



#define LLNET_ASSEMBLY_VERSION  TO_VERSION_STRING(LLNET_VERSION_MAGOR.LLNET_VERSION_MINOR.LLNET_VERSION_REVISION.*)

#define LLNET_ASSEMBLY_FILE_VERSION  TO_VERSION_STRING(LLNET_VERSION_MAGOR.LLNET_VERSION_MINOR.LLNET_VERSION_REVISION.0)