#pragma once

#define LLNET_INFO_LOADER_NAME "LiteLoader.NET"

#define LLNET_INFO_LOADER_DESCRIPTION "LiteLoader bindings for .NET"

#define LLNET_INFO_AUTHOR "LiteLoaderBDS .NET Developers"

#define LLNET_INFO_COPYRIGHT "Copyright (c) 2020-2023 LiteLoaderBDS Developers"



#define LLNET_VERSION_MAJOR 2

#define LLNET_VERSION_MINOR 10

#define LLNET_VERSION_REVISION 0

#define LLNET_VERSION_BUILD 0

#define LLNET_VERSION_ACTIONS 0

#define LLNET_VERSION_STATUS PLUGIN_VERSION_DEV

#define LLNET_ASSEMBLY_VERSION  TO_VERSION_STRING(LLNET_VERSION_MAJOR.LLNET_VERSION_MINOR.LLNET_VERSION_REVISION.*)

#define LLNET_ASSEMBLY_FILE_VERSION  TO_VERSION_STRING(LLNET_VERSION_MAJOR.LLNET_VERSION_MINOR.LLNET_VERSION_REVISION.LLNET_VERSION_BUILD)
