#pragma once

using System::Console;
using System::GC;
using System::IntPtr;
using System::String;
using System::Object;
using System::Exception;
using System::Collections::Generic::Dictionary;
using System::Collections::Generic::List;
using System::Collections::Generic::KeyValuePair;
using System::Collections::Generic::Queue;
using System::Reflection::Assembly;
using System::Reflection::AssemblyName;
using System::Runtime::InteropServices::FieldOffsetAttribute;
using System::Runtime::InteropServices::GCHandle;
using System::Runtime::InteropServices::LayoutKind;
using System::Runtime::InteropServices::Marshal;
using System::Runtime::InteropServices::StructLayoutAttribute;
using System::Runtime::InteropServices::OutAttribute;
using System::Runtime::InteropServices::InAttribute;
using System::Runtime::CompilerServices::MethodImplAttribute;
using System::Runtime::CompilerServices::MethodImplOptions;